//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travellingyuan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("travellingyuan.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DialogOk {
            get {
                return ResourceManager.GetString("DialogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOOPS!.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred, try again.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ExceptionTitle {
            get {
                return ResourceManager.GetString("ExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication error: {0}.
        /// </summary>
        internal static string HttpRequestExceptionMessage {
            get {
                return ResourceManager.GetString("HttpRequestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string HttpRequestExceptionTitle {
            get {
                return ResourceManager.GetString("HttpRequestExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email can&apos;t be empty.
        /// </summary>
        internal static string NoEmail {
            get {
                return ResourceManager.GetString("NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t retrieve any result, please try again or type manually.
        /// </summary>
        internal static string NoMatch {
            get {
                return ResourceManager.GetString("NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid phone number.
        /// </summary>
        internal static string NoPhone {
            get {
                return ResourceManager.GetString("NoPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No picture was found, please try again.
        /// </summary>
        internal static string NoPicture {
            get {
                return ResourceManager.GetString("NoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource you are looking for has been removed, had its name changed, or is temporarily unavailable..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access code can&apos;t be empty.
        /// </summary>
        internal static string NoToken {
            get {
                return ResourceManager.GetString("NoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twilio Error 21612 - https://www.twilio.com/docs/errors/21612.
        /// </summary>
        internal static string TwillioError {
            get {
                return ResourceManager.GetString("TwillioError", resourceCulture);
            }
        }
    }
}
